// Assignment Code
var generateBtn = document.querySelector("#generate");
generateBtn.addEventListener("click", writePassword);

// Begins process and asks for number of characters
function generatePassword() {
  let length = prompt("How many characters do you want your password to be?", "Choose 8-128")
  while (length < 8 || length > 128 || isNaN(length)) {length = prompt('Please enter a number between 8-128')}

// Asks for lower case characters
  let lower = confirm("Do you want your password to include lower case letters?")

// Asks for upper case characters
  let upper = confirm("Do you want your password to include upper case letters?")

// Asks for numeric characters
  let numeric = confirm("Do you want your password to include numbers?")

// Asks for special characters
  let special = confirm("Do you want your password to include special characters?")

  // Establishes an array of possibilities for each variable
let lowerLetters = 'abcdefghijklmnopqrstuvwxyz';
let capLetters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
let numbers = '1234567890';
let specialChars = '!@#$%^&*()';

// Stores and combines the user's choices on passord characters
let password = "";

if (lower) {
  password = password += lowerLetters;
}
if (upper) {
  password = password += capLetters;
}
if (numeric) {
  password = password += numbers;
}
if (special) {
  password = password += specialChars;
}

// Convenience variable to "catch" data returned from the function
createPassword = ""

// Random number generator iterates a number of times = length along the string generated by the user
  for (var i = 0; i < length; i++) {
    createPassword += password[Math.floor(Math.random() * password.length)]
  } return createPassword};

// Writes the password to the prompt box
function writePassword() {
  let password = generatePassword();
let passwordText = document.querySelector("#password");
passwordText.value = password;
};